
name: pest
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pandas
  - seaborn
  - imageio
  # - dill
  # - joblib
  # - h5py
  # - numexpr
